config/routes.rb
Rails.application.routes.draw do
  root 'users#show'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    resources :rockles, only: [:new, :create]
  end
  resources :rockles, only: [:index, :show]

  get '/rockle/fight/:id', to: "rockles#fight", as: "rockle_fight"

end

app/models/rockle.rb
# == Schema Information
#
# Table name: rockles
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  species    :string(255)      not null
#  user_id    :integer          not null
#  level      :integer          default(1)
#  exp        :integer          default(0)
#  max_hp     :integer
#  hp_points  :integer          default(0)
#  atk_points :integer          default(0)
#  def_points :integer          default(0)
#  spd_points :integer          default(0)
#  created_at :datetime
#  updated_at :datetime
#

class Rockle < ActiveRecord::Base
  SPECIES = %w(a b c d e)
  validates :species, presence: true, inclusion: SPECIES
  validates :name, :user_id, presence: true

  belongs_to :user

  after_create :roll_stats
  after_create :compute_stats


  private

  def compute_stats
    self.update_attribute(:max_hp, self.hp_points * 10)
  end

  def roll_stats
    attr_hash = {hp_points: "", atk_points: "", def_points: "", spd_points: ""}
    %w(hp_points atk_points def_points spd_points).each do |attr|
      attr_hash[attr] = rand(5..10)
    end
    self.update_attributes(attr_hash)
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  gold            :integer          default(100)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password

  before_validation :ensure_session_token

  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}

  has_one :rockle

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    if user.nil? || !user.is_password?(password)
      return nil
    end
    return user
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    unless password.nil?
      @password = password
      self.password_digest = BCrypt::Password.create(password)
    end
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def ensure_signed_in
    redirect_to new_session_url unless signed_in?
  end

  def ensure_signed_out
    redirect_to root_url if signed_in?
  end

  def signed_in?
    !!current_user
  end

  def signin_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def signout_user!
    session[:session_token] = nil
  end
end

app/controllers/rockles_controller.rb
class RocklesController < ApplicationController
  before_action :ensure_signed_in

  def new
    @species = %w(a b c d e)
    @rockle = Rockle.new
    @user_id = current_user.id

  end

  def index
    @rockles = Rockle.all

    @rockles.each do |rockle|
      rockle.user = User.find(rockle.user_id)
    end
    render 'index'
  end

  def create
    @rockle = Rockle.new(name: params[:rockle][:name], species: params[:rockle][:species])
    @rockle.user_id = current_user.id

    if @rockle.save
      redirect_to rockle_url(@rockle)
    else
      flash[:error] = @rockle.errors.full_messages
      redirect_to new_user_rockle_url(current_user)
    end
  end

  def show
    @rockle = Rockle.find(params[:id]) #TODO: check params
    @rockle.user = User.find(@rockle.user_id)
  end

  private

  def rockle_params
    params.require(:rockle).permit(:name, :species)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_signed_out, except: [:destroy]

  def new
    @user = User.new
    render 'new'
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      signin_user!(@user)
      redirect_to root_url
    else
      @user = User.new(username: params[:user][:username])
      flash.now[:error] = ["Invalid username/password combo"]
      render 'new'
    end
  end

  def destroy
    signout_user!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_signed_out, only: [:new, :create]
  before_action :ensure_signed_in, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      signin_user!(@user)
      redirect_to root_url
    else
      flash.now[:error] = @user.errors.full_messages
      render 'new'
    end
  end

  def show
    @user = current_user
    @user.rockle = Rockle.find_by({user: User.find(@user.id)})
    render 'show'
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<%= current_user.username %> | <%= link_to "Log Out", session_url, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RockleGame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless current_user.nil? %>
  <%= render partial: "layouts/header" %>
<% end %>

<% flash.each do |key, value| %>
  <div class="flash <%= key %>">
    <ul>
      <% if value.is_a?(String) %>
        <li><%= value %></li>
      <% else %>
        <% value.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/rockles/index.html.erb
<ul>

  <% @rockles.each do |rockle| %>

<li><%= rockle.name %>:
  <br/>
  <span>Owner: <a href="<%= user_url({id: rockle.user.id}) %>"><%= rockle.user.username %></a></span>
  <span>Level: <%= rockle.level %></span>
  <span>Exp: <%= rockle.exp %></span>
  <span>Max HP: <%= rockle.max_hp %></span>
  <span>ATK: <%= rockle.atk_points %></span>
  <span>DEF: <%= rockle.def_points %></span>
  <span>SPD: <%= rockle.spd_points %></span>
  <span>HP: <%= rockle.hp_points %></span>
</li>

<% end %>

</ul>

app/views/rockles/index.html.haml
%h1 Challenge a Rockle!
%table
  %thead
    %th
    %th Name
    %th Level
    %th Owner
    %th
  %tbody
    -@rockles_in_range.each do |rockle|
      %tr
        %td= image_tag rockle.image_url, :style => 'width:50px;'
        %td= rockle.name
        %td= rockle.level
        %td= rockle.user.username
        %td= link_to "FIGHT!", rockle_fight_path(rockle)

app/views/rockles/new.html.erb
<h1>New Rockle</h1>
<form role="form" id="new-rockle" action="<%= user_rockles_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% @species.each do |type| %>
    <label for="species-<%= type %>">Species: <%= type %></label>
    <input type="radio"
           id="species-<%= type %>"
           name="rockle[species]"
           value="<%= type %>">
  <% end %>
  <br>
  <label for="rockle-name">Name: </label>
  <input type="text"
         id="rockle-name"
         name="rockle[name]">
  <br>
  <button type="submit">Select</button>
</form>

app/views/rockles/show.html.erb
<h1><%= @rockle.name %></h1>
<ul>
  <li>Owner: <a href="<%= user_url(@rockle.user_id)%>"><%= @rockle.user.username%></a></li>
  <li>Level: <%= @rockle.level %></li>
  <li>Exp: <%= @rockle.exp %></li>
  <li>Max HP: <%= @rockle.max_hp %></li>
  <li>ATK: <%= @rockle.atk_points %></li>
  <li>DEF: <%= @rockle.def_points %></li>
  <li>SPD: <%= @rockle.spd_points %></li>
  <li>HP: <%= @rockle.hp_points %></li>
</ul>

app/views/shared/_user_form.html.erb
<form role="form" id="user-form" action="<%= desired_action %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="username">Username: </label>
  <input type="text"
         name="user[username]"
         id="username"
         value="<%= user.username %>">
  <br>
  <label for="password">Password: </label>
  <input type="password"
         name="user[password]"
         id="password">
  <br>
  <button type="submit">Submit</button>
</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render partial: "shared/user_form", locals: { user: @user, desired_action: users_url } %>
<%= link_to "Log in here", new_session_url %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>
Gold: <%= @user.gold%>


<br>
<% if @user.rockle.present? %>
Rockle: <%= link_to @user.rockle.name, rockle_url({id: @user.rockle.id}) %>
<% else %>
<a href="<%= new_user_rockle_url({user_id: @user.id}) %>">Create your rockle!</a>
<% end %>